export const seoKeywords = [
  "Full Stack Developer in Mumbai",
  "Software Engineer in Mumbai",
  "React Developer",
  "Next.js Developer",
  "Node.js Developer",
  "Python Developer",
  "Django Developer",
  "REST API Developer",
  "Front-end Developer",
  "Back-end Developer",
  "React Native Developer",
  "MERN Stack Developer",
  "Microservices Developer",
  "Cloud Developer",
  "AWS Developer",
  "GCP Developer",
  "Docker Developer",
  "Machine Learning Engineer",
  "Data Engineer",
  "Portfolio",
  "System Design",
  "Secure API Development",
  "WebSocket Developer",
  "Agile Development",
  "Real-Time Data",
  "Database Design",
  "Software Development",
  "Scalable Web Apps",
  "Fullstack Developer",
  "JavaScript Developer",
  "CSS Developer",
  "Web Developer",
  "UI/UX Developer",
  "Web Developer in Mumbai",
];
